In [49]:
import numpy as np

print(np.empty((2,3)))#garbage value

[[0. 0. 0.]
 [0. 0. 0.]]


In [47]:
print(np.full(8,10))

arr= np.full((3,4),7)
print(arr)

[10 10 10 10 10 10 10 10]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [42]:
#Array Initialization ---------------------------------------------------------------------------------------------------------------------------
  #zeros --------
import numpy as np
#1 D array
print(np.zeros(5))

#2 D array
print(np.zeros((2, 3),dtype=int))

#3 D array
print(np.zeros((2, 3, 4)))

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [37]:
import numpy as np
array_1 = np.array(range(1, 21))
even_num = array_1[array_1 % 2 == 0]
print(even_num)

array_2 = np.array([10, 20, 30, 40, 50])
result_arr = array_2[np.mean(array_2) < array_2]
print(result_arr)

[ 2  4  6  8 10 12 14 16 18 20]
[40 50]


1.create a 1D numpy array from 1 to 20
   1.1 use boolean index into extract all even number
2.Given the numpy array with elements 10,20,30,40,50,use boolean index into extract all elements greter than the mean of the array

In [32]:
arr = np.array([10, 20, 30, 40, 50])
condition = arr > 25
print(condition)
result_arr = arr[condition]
print(result_arr)

[False False  True  True  True]
[30 40 50]


In [26]:
import numpy as np
array_1 = np.array([
                    [1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]
                ])
add_10 = array_1 + 10
multiply =  array_1 * 2
square_num = array_1 ** 2
print (array_1)
print(add_10)
print(multiply)
print(square_num)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]]


create a 2d num.py array with the shape 4 by 5 containing the numbers 1-20
perform the following opertions on the above matrics
       1. add 10 to every element
       2. multiply 2 every element
       3. calculate square of each element

In [24]:
import numpy as np
array_1 = np.array([[1,2,3],[4,5,6]])
print(array_1)
print(array_1.shape) #get dimension
print(array_1.size) #induvidual element (number of elements)
print(array_1.ndim) #number of dimensions
print(array_1.dtype)

array_2 = np.array([
                        [ [1,2,3],[4,5,6] ] ,
                        [ [7,8,9],[10,11,12] ] 
                    ])
print(array_2.shape)
print(array_2.size)
print(array_2.ndim)
print(array_2.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
int64
(2, 2, 3)
12
3
int64


In [15]:
import numpy as np
array_1 = np.array([6,10,11,1])
array_2 = np.array([5,9,10,4])
array_3 = np.array([25,64,4])
sum_array = array_1 + array_2
min_array = array_1 - array_2
multi_array = array_1 * array_2 
div_array = array_1/array_2
print(sum_array, min_array, multi_array,div_array)

square_num_array_1 = array_1 ** 2
print(square_num_array_1)

square_root = np.sqrt(array_3)
sum = np.sum(array_3)
mean = np.mean(array_3)
max = np.max(array_3)
min = np.min(array_3)
print(square_root)
print(sum)
print(mean)
print(max, min)

[11 19 21  5] [ 1  1  1 -3] [ 30  90 110   4] [1.2        1.11111111 1.1        0.25      ]
[ 36 100 121   1]
[5. 8. 2.]
93
31.0
64 4


In [6]:
import numpy as np
array_1 = np.array([6,10,11,1])
print(array_1,type(array_1))

[ 6 10 11  1] <class 'numpy.ndarray'>
