In [15]:
import numpy as np
array_1 = np.array([6,10,11,1])
array_2 = np.array([5,9,10,4])
array_3 = np.array([25,64,4])
sum_array = array_1 + array_2
min_array = array_1 - array_2
multi_array = array_1 * array_2 
div_array = array_1/array_2
print(sum_array, min_array, multi_array,div_array)

square_num_array_1 = array_1 ** 2
print(square_num_array_1)

square_root = np.sqrt(array_3)
sum = np.sum(array_3)
mean = np.mean(array_3)
max = np.max(array_3)
min = np.min(array_3)
print(square_root)
print(sum)
print(mean)
print(max, min)

[11 19 21  5] [ 1  1  1 -3] [ 30  90 110   4] [1.2        1.11111111 1.1        0.25      ]
[ 36 100 121   1]
[5. 8. 2.]
93
31.0
64 4


In [6]:
import numpy as np
array_1 = np.array([6,10,11,1])
print(array_1,type(array_1))

[ 6 10 11  1] <class 'numpy.ndarray'>
